### PR TITLE
Support for non-ascii/utf-8 charsets

### PR DESCRIPTION
**Pull request by plexus**
And one more ... :)

Let me know if you like these changes or not, or if you have any feedback. This is the last one for now.

When encountering a Content-Type:...; charset=... header, use it to switch to
the correct coding system.

### CODE REVIEW

**Comment by hassy** [comment]
Awesome patches, thanks!

**Comment by hassy** [comment]
Ah it has conflicts now that I merged the other PR, mind fixing up the conflicts? :)

**Comment by plexus** [comment]
That's what you get for nicely splitting things in separate PR's :) I rebased, it should be mergeable now.

**Comment by plexus** [comment]
Great project BTW! I'll be showing it off on https://lambdaisland.com :)

**Comment by hassy** [comment]
👍  thanks! 

Most of the credit for `http-twiddle` should go to Luke Gorrie, the original author. I just gave it a permanent home. :)

lambdaisland.com looks nice!

**Pull request merged**
